name: snake-hs
version: 0.1.0.0
github: 'ddowl/snake-hs'
license: BSD3
author: 'Drew Dowling'
maintainer: 'drewdowling37@gmail.com'
copyright: '2020 Drew Dowling'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ddowl/snake-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - containers
  - vty
  - lens
  - random

library:
  source-dirs: src

executables:
  snake-hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - snake-hs

tests:
  snake-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - snake-hs
